name: test_prj
description: "App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  email_validator: ^3.0.0
  build_runner: ^2.4.12
  loader_overlay: ^4.0.2+1
  overlay_support: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  faker: ^2.2.0
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  generate: true




